line_length:
- 300 #warning
- 400 #error

excluded:
- Pods
- Carthage

disabled_rules:
- unused_optional_binding
- function_body_length
- file_length
- operator_whitespace
- identifier_name
- type_body_length
- deployment_target
- for_where
- cyclomatic_complexity
- weak_delegate
- nesting
- trailing_whitespace
- class_delegate_protocol
